const test = {
  userID: "Admin",
  userName: "Admin",
  userPassword: "123",
  userType: "Standard",
  enabled: true,
  admin: true,
  changePassword: true,
  workflowRoleID: null,
  entityID: null,
  email: null,
  createdBy: null,
  createdOn: null,
  modifiedBy: null,
  modifiedOn: null,
  workflowRole: null,
  entity: null,
  usersSecurityRoles: [
    {
      userID: "Admin",
      securityRoleID: "01",
      startDate: "2024-01-16T10:12:14.536",
      endDate: "2024-01-31T16:14:12.904",
      allEntities: false,
      status: "updated",
      securityRole: {
        securityRoleID: "01",
        securityRoleName: "New Role",
        description: null,
        securityRolesTasks: null,
        securityRolesPrivileges: null,
      },
      usersSecurityRolesEntities: [
        {
          userID: "Admin",
          securityRoleID: "01",
          status: "new",
          entityID: "001",
          entity: {
            entityID: "001",
            entityName: "Main Company",
            entityType: "Company",
            companyID: null,
            commercialRegisteration: null,
            taxRegistration: null,
            currencyID: null,
            salesTaxGroupID: null,
            description: null,
            currency: null,
            salesTaxGroup: null,
            legalEntitiesContacts: null,
            legalEntitiesAddresses: null,
          },
        },
      ],
    },
  ],
};
